server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/customer/**
          filters:
            - name: AuthenticationFilter
        - id: BENEFICIARY-SERVICE
          uri: lb://BENEFICIARY-SERVICE
          predicates:
            - Path=/v1/beneficiary/**
          filters:
            - name: AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8772/eureka/

logging:
  level:
    root: INFO
    com.iconsult.apigateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
